[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.2.0"
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/RompEmu/RompEmu"

[workspace.dependencies]
romp-libretro = { path = "crates/romp-libretro" }
romp-proto = { path = "crates/romp-proto" }

[profile.release]
codegen-units = 1
