[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.8.0"
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/RompEmu/RompEmu"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "warn"

[workspace.lints.clippy]
cast_lossless = "warn"
semicolon_if_nothing_returned = "warn"
redundant_closure_for_method_calls = "warn"
uninlined_format_args = "warn"

[workspace.dependencies]
romp-cheevos = { path = "crates/romp-cheevos" }
romp-libretro = { path = "crates/romp-libretro" }
romp-proto = { path = "crates/romp-proto" }

[profile.dev]
debug = "line-tables-only"

[profile.dev.package."*"]
debug = false

[profile.release]
codegen-units = 1
